export default {
  Name: "Foxis the Cookie Dragon",
  Route: "/dragon",
  Description:
    "Foxis The Cookie Dragon, Judah's dragon self. Images and references for my dragon. Has both Feral and Humanoid forms.",
  Attributes: [
    { id: "Gender", value: "Male" },
    { id: "Age", value: "25" },
    { id: "Height", value: "Big" },
    { id: "Dragon", value: "Yes" },
    { id: "Actual Height", value: "8-12 feet" },
  ],
  FeaturedImage: "/images/2018/10_12_1judahlineless.png",
  Types: ["feral", "anthro", "reference"],
  Images: [
    {
      title: "The Cookie Dragon",
      href: "images/commission___baby_dragon_by_raizy-d6xqz3x.png",
      description:
        'Original Commission from Chu based on Tom\'s <a target="_blank" href="https://www.deviantart.com/twokinds/art/Hatchling-189738877">dragon hatchling art</a>. Most of these early images are from Chu.',
      type: "feral",
      year: 2013,
    },
    {
      title: "The Cookie Dragon",
      href: "images/9-judah.png",
      type: "feral",
      description: "First proper colors for Foxis! From Chu.",
      year: 2014,
    },
    {
      title: "Dragon April",
      href: "images/chu_dragon_April_2016.png",
      type: "feral",
      year: 2016,
    },
    {
      title: "Dragon May",
      href: "images/chu_dragon_May_2016.png",
      type: "feral",
      year: 2016,
    },
    {
      title: "Cookie Dragon",
      href: "images/dragon1Apple.png",
      description: "Commissioned from Appledapple!",
      type: "feral",
    },
    {
      title: "Birthday Dragon",
      href: "images/2017/chu_dragon_birthday_2017.jpg",
      description: "Commissioned from Chu!",
      type: "feral",
      year: 2017,
    },
    {
      title: "Christmas Cookie Dragon",
      href: "images/dragonChristmas.png",
      description: "Commissioned from Appledapple!",
      type: "feral",
    },
    {
      title: "Halloween Cookie Dragon",
      href: "images/holloweenDragon.png",
      description: "Dragon dressed as a charmander for halloween",
      type: "feral",
    },
    {
      title: "Christmas Cookie Dragon",
      href: "images/judah4-christmas_cookie_dragon.png",
      type: "feral",
    },
    {
      title: "Sleeping Dragon",
      href: "images/judah4---sleeping-dragon-animation.gif",
      description: "Animated sleeping dragon. Very tired.",
      type: "feral",
      year: 2017,
    },
    {
      title: "ZZZ... Dragon",
      href: "images/UpsideDownDragon.jpg",
      description: "The dragon is even more tired.",
      type: "feral",
      year: 2017,
    },
    {
      title: "Circle Dragon",
      href: "images/judah-circle_dragon.png",
      type: "feral",
    },
    /*{
            title: 'Cookie Dragon Games Logo',
            href: 'images/CookieDragon2_Color.png',
            description: 'The logo for my single person game studio!',
            type: "feral",
        },*/
    {
      title: "Lineless Icon",
      href: "images/2018/10_12_1judahlineless.png",
      description: "Icon from @faunbutt",
      type: "feral",
      year: 2018,
    },
    {
      title: "Neon Badge",
      href: "images/2019/1-JudahNeonBadge.jpg",
      description: "Badge from https://twitter.com/Lumaberry",
      type: "feral",
      year: 2019,
    },
    {
      title: "TwoKinds Discord Server Group Picture",
      href: "images/2019/Judah-Moon_ForPosting.png",
      description: "Group picture of the Discord group! Thank you Neon!",
      type: "feral",
      year: 2019,
    },
    {
      title: "Chibi Dragon",
      href: "images/2020/frogbuttdragon.png",
      description: "From https://twitter.com/TheFrogButt. January 2020",
      type: "feral",
      year: 2020,
    },
    {
      title: "Dragon Emotes",
      href: "images/2020/frostDragonEmotes.jpg",
      description: "From https://twitter.com/Elegantlyfrost. March 2020",
      type: "feral",
      year: 2020,
    },
    {
      title: "Cookie Dragon With Cookies",
      href: "images/2020/OtherEric_CookieDragon_Commish.png",
      description: "From TheOtherEric. December 2020",
      type: "anthro",
      year: 2020,
    },
    {
      title: "Metal Emotes!",
      href: "images/dragon/2021/metal_emotes1.png",
      description: "Emotes from Metal.",
      type: "feral",
      year: 2021,
    },
    {
      title: "More Metal Emotes!",
      href: "images/dragon/2021/metal_emotes2.jpg",
      description: "More Emotes from Metal.",
      type: "feral",
      year: 2021,
    },
    {
      title: "Gift Art From Neon Mitsumi",
      href: "images/dragon/2022/2022-06-CookieDragon-NeonGiftArt.png",
      description: "Gift art from Neon Mitsumi! Thank you!",
      type: "feral",
      year: 2022,
    },
    {
      title: "Little Dragon Commission",
      href: "images/dragon/2022/cookieLittleDragon-2022-07.png",
      description:
        'Lil Dragon Commision from Hexephre! <a href="https://hexephre.carrd.co/">https://hexephre.carrd.co/</a>',
      type: "feral",
      year: 2022,
    },
    {
      title: "Gift Art From Iliar",
      href: "images/dragon/2022/2022-09-iliarGift.png",
      description: "A gift from Iliar! Thank you!",
      type: "anthro",
      year: 2022,
    },
    {
      title: "Christmas Gift Art From Nextament",
      href: "images/dragon/2022/2022-NextXmas.png",
      description: "A Christmas gift from Nextament! Thank you!",
      type: "feral",
      year: 2022,
    },
    {
      title: "Gift Birthday Art From Nextament",
      href: "images/dragon/2023/2023-02-Dragon-NextBirthday.png",
      description: "A birthday gift from Nextament! Thank you!",
      type: "feral",
      year: 2023,
    },
    {
      title: "Gift Father's Day Art From Corgi",
      href: "images/dragon/2023/2023-06-Corgi-CookieGift.jpg",
      description: "A Fathers Day gift from Corgi! Thank you!",
      type: "anthro",
      year: 2023,
    },
    {
      title: "Victory Sign Commission",
      href: "images/dragon/2023/2023-07-ScruffyBrush-CookieDragonVictory.png",
      description:
        'A commission from <a href="https://meow.social/@ScruffyBrush" >ScruffyBrush (https://meow.social/@ScruffyBrush)</a>. Foxis is doing the victory sign.',
      type: "anthro",
      year: 2023,
    },
    {
      title: "TwoKinds Discord Server Neon Gift",
      href: "images/dragon/2023/2023-07-Twokinds_Server_Gift_Commission_2023_CookieDragon.png",
      description:
        'Gift art from Neon Mitsumi! Thank you! Here is the full version of  be found at <a href="images/dragon/2023/2023-07-Twokinds_Server_Gift_Commission_2023_HQ.png" >Twokinds Server Gift Commission</a>.',
      type: "anthro",
      year: 2023,
    },
    {
      title: "Character Reference",
      href: "images/dragon/2023/2023-09-Foxis_Feral_Scales.png",
      thumb: "images/dragon/2023/2023-09-Foxis_Feral_Scales_Resized.jpg",
      description: "Character reference commission from Seth Knight.",
      type: "feral",
      collections: ["feral", "reference"],
      year: 2023,
    },
    {
      title: "Huevember 2023",
      href: "images/dragon/2023/2023-10-Foxis_Huevember.png",
      description:
        'A commission from <a href="https://mastoart.social/@L" >L James (https://mastoart.social/@L)</a> for Huevember. The colors are vibrant.',
      type: "feral",
      year: 2023,
    },
    {
      title: "Tsukinori Neon Gift Art Comission - Foxis and Adira",
      href: "images/dragon/2024/2024-01-tsukinori-17 and 27 - CookieDragon and Adira.png",
      description:
        'A commission from <a href="https://www.furaffinity.net/user/tsukinori/" >Tsukinori</a> for Neon as a gift from all of us. You can view the full version at <a href="https://www.furaffinity.net/view/55104441/">Tsukinori\'s FurAffinity post.</a>',
      type: "feral",
      year: 2024,
    },
  ],
};
